void _mkdir( char *);
void send_file(int , char *, char *, char *);
void recvfile(int, char * );
void send_dir(int, char *, char *);
void delete_file_path(int  , char *);
void create_folder_path(int , char *);
void delete_folder_path(int , char *);
void delete_file_path(int , char *);
void send_file_path(int , char *, char *, char *);
void rm_dir(char *, char *);
